### ISSUE TITLE
EOFError raised when creating environment

### ISSUE THREAD

**Issue by angelazhx** [ColinKohler/BulletArm#1]
really good framework for robot manupulation!
but there are some environment files with no _init_.py file that casued issue
now I'm facing issue with
File "/home/usr1/bash/envs/bulletarm/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
for both open loop and close loop environments Benchmarks, any ideas how to fix this? thanks a lot

**Comment by angelazhx** [comment]
hi pointW
thanks for your reply. 
the issue happened with I'm running main.py in bulletarm_baseline direcorty 

python main.py --algorithm=[algorithm] --architecture=[architecture] --env=[env]

tried with different envs eg. block_stacking and deconstruct

error shows:
File "/home/usr1/bash/envs/bulletarm/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError

is there any suggestion how to fix this? thx

**Comment by angelazhx** [comment]
> What system are you using? I could not reproduce this problem on Ubuntu18 with Python 3.9. The script I ran was `python main.py --algorithm=sdqfd --architecture=cnn_asr --env=block_stacking --fill_buffer_deconstruct` under `bulletarm_baselines/fc_dqn/scripts`

Hi pointW

I'm using Operating System: Ubuntu 22.04 LTS                               
          Kernel: Linux 5.15.0-40-generic
    Architecture: x86-64
 Hardware Vendor: Razer
  Hardware Model: Blade 15 Advanced Model _Early 2021_ - RZ09-036
 with conda environment Python 3.9. 
and I was running 
python main.py --algorithm=sdqfd --architecture=cnn_asr --env=block_stacking --fill_buffer_deconstruct  
under bulletarm_baselines/fc_dqn/scripts for the open loop benchmark. 

thx

**Comment by angelazhx** [comment]
> Two more quick questions:
> 
> 1. Can you run the block stacking demo?
> 2. If the answer to (1) is no, can you try to change the 1 in Line 5 to a 0. This will run BulletArm in the main thread so we will know if you issue is due to multiprocessing.

hi ColinKohler

thanks for your reply. 
I was having same EOFError when I run the demo,with 
Install this package
pip install .

then I added to PYTHONPATH
export PYTHONPATH=/path/to/BulletArm/:$PYTHONPATH
and I could run the demo then. 

But I tried with Open-Loop benchmark under bulletarm_baselines/fc_dqn/scripts, same EOFError persists. 

thx

**Comment by ColinKohler** [comment]
The fact that you were able to run the demo after adding BulletArm to your path but then got the same error with the baselines is a bit strange. Could you please double check that when you ran the baselines BulletArm was still in your python path? 

Otherwise, it sounds to me like there is something weird going on with your python imports or pip. You could try to create a new Anaconda environment from scratch?
