### ISSUE TITLE
about tutorials

### ISSUE THREAD

**Issue by xumingkun9806** [ColinKohler/BulletArm#2]
Thanks for your excellent work，in the tutorials，baseline_demo.py ,creating_a_new_robot.py is empty，when you update？

**Comment by ColinKohler** [comment]
Hello, thanks for the interest in our work! If there is interest I can put out a tutorial on creating a new robot fairly soon. We were going to wait for v1.1 as I expect the API to change a decent amount but I don't mind writing a quick tutorial for this now if you need it. As far as the baseline demo goes, at the moment we are unsure if this is necessary as the documentation covers running the baselines fairly comprehensively, see [here](https://colinkohler.github.io/BulletArm/api/bulletarm_baselines.html) for details. If you think something important here is missing please let me know.

**Comment by xumingkun9806** [comment]
Ok，thank you ！
