### ISSUE TITLE
how to get image observation while running headless

### ISSUE THREAD

**Issue by mlzxy** [ColinKohler/BulletArm#6]
Hi, I wonder is it possible to get image observation of the environment while running headless? 

Thanks!

**Comment by ColinKohler** [comment]
By image observation do you mean the rgb/depth images produced by the sensors? If so then yes, the sensors should work fine headless.

**Comment by mlzxy** [comment]
> By image observation do you mean the rgb/depth images produced by the sensors? If so then yes, the sensors should work fine headless.

Got it. So if I want another viewpoint, e.g., simulate the screenshot, I could modify the camera parameter of the sensor right?

**Comment by ColinKohler** [comment]
Yup. The sensing code needs a bit of a cleanup but if you look at `bulletarm/pybullet/utils/sensor.py` you can see that the sensor takes the sensor position (where the sensor is) along with the target position (where the sensor is pointing at). You may need to fiddle w/the other parameters depending on what your doing but I would start w/just the two positions.

**Comment by ColinKohler** [comment]
Closing. Feel free to open if there are additional issues.
